### ISSUE TITLE
Using this with hx-post

### ISSUE THREAD

**Issue by divSelector** [bblanchon/django-htmx-messages-framework#7]
Hey, thanks for writing the article and the code.

I've been trying to get this to work in response to a `hx-post`

```
    <a class="btn btn-lg btn-info fw-bold border-white bg-primary"
      href="javascript:void(0)"
      aria-current="page"
      hx-post="{{ login_url }}"
      hx-target="body"
      hx-push-url="true"
      hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
      Log In
  </a>
```

On login and logout, I'll have the appropriate "You signed in" / "You logged out" messages logging in the console, but they won't toast. However if I switch to `hx-get="/message"` it will work.

My guess is that it has something to do with what is currently loaded in the DOM when it gets the createToast call.

I'm pretty new to this. I thought maybe you would have an idea. If not, thanks anyway.

**Comment by bblanchon** [comment]
Hi @divSelector,

This could be due to a redirect.
Ensure you don't include the messages in the redirect response so that they will be sent with the next GET.
https://github.com/bblanchon/django-htmx-messages-framework/blob/165362040ff9b3730dc87bdbfadc9218f63a9f69/htmx_messages/middleware.py#L18-L20

Best regards,
Benoit
